name: jpec_sama
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  dio: ^5.5.0+1
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.8.0
  cupertino_icons: ^1.0.8
  go_router: ^14.2.1
  equatable: ^2.0.5
  image_picker: ^1.0.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_localizations:
    sdk: flutter
  # flutter_local_notifications: ^17.2.1+2
  awesome_notifications: ^0.9.3+1
  intl: any
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # flutter_html: ^2.2.1
  #https://pub.dev/packages/country_code_picker
  country_code_picker: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  fl_chart: ^0.68.0
  sentry_flutter: ^8.6.0
  timezone: ^0.9.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  workmanager: ^0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  flutter_launcher_icons: "^0.13.1"

analyzer:
  errors:
    invalid_annotation_target: ignore

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/