// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1NwDYNM8S01wb8qtrWvzdY3MZKn5cOw',
    appId: '1:326582914917:web:018d99e9298a6be9e91b8c',
    messagingSenderId: '326582914917',
    projectId: 'jpecsama',
    authDomain: 'jpecsama.firebaseapp.com',
    storageBucket: 'jpecsama.appspot.com',
    measurementId: 'G-6Q6RB79TBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSvAoV5Nka4M95csCWrpE_ot8L_M-C6A',
    appId: '1:326582914917:android:fab35e455ab4dd74e91b8c',
    messagingSenderId: '326582914917',
    projectId: 'jpecsama',
    storageBucket: 'jpecsama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_G27j_LGZ82zIhh_zeYyw4ZT6CiGywo',
    appId: '1:326582914917:ios:b1eada15aa8e0ffde91b8c',
    messagingSenderId: '326582914917',
    projectId: 'jpecsama',
    storageBucket: 'jpecsama.appspot.com',
    iosBundleId: 'com.jpec57.jpecSama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_G27j_LGZ82zIhh_zeYyw4ZT6CiGywo',
    appId: '1:326582914917:ios:b1eada15aa8e0ffde91b8c',
    messagingSenderId: '326582914917',
    projectId: 'jpecsama',
    storageBucket: 'jpecsama.appspot.com',
    iosBundleId: 'com.jpec57.jpecSama',
  );
}
